import { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    dashboard: 'Dashboard',
    pricePrediction: 'Price Prediction',
    demandForecast: 'Demand Forecast',
    marketLocator: 'Market Locator',
    cropAdvisor: 'Crop Advisor',
    storageAdvice: 'Storage Advice',
    news: 'News',
    yojana: 'Yojana',
    livePriceTracker: 'Live Price Tracker',
    currentWeather: 'Current Weather',
    moisture: 'Moisture',
    phLevel: 'pH Level',
    activityLog: 'Activity Log',
    today: 'Today',
    yesterday: 'Yesterday',
    automatedIrrigation: 'Automated Irrigation',
    irrigationDone: 'Zone A irrigation completed successfully.',
    nitrogenApplication: 'Nitrogen Application',
    nitrogenDone: 'Applied nitrogen fertilizer to Sector 3.',
    activeAlerts: 'Active Alerts',
    frostWarning: 'Frost Warning (Night)',
    frostDesc: 'Temperatures dropping below 4°C tonight. Protect sensitive crops.',
    irrigationReminder: 'Irrigation Reminder',
    irrigationDesc: 'Soil moisture is dropping in Zone B.',
    farmManager: 'Farm Manager',
    profileSettings: 'Profile Settings',
    optimalRange: 'Optimal range: 60-70%',
    nutrientIndex: 'Nutrient Index',
    nutrientDesc: 'View detailed NPK ratio analysis',
    partlyCloudy: 'Partly Cloudy',
    humidity: 'Humidity',
    rainfall: 'Rainfall',
    wind: 'Wind',
    perQuintal: 'per quintal',
    cropSubstitle: 'Get personalized crop suggestions based on your environment',
    checkWeatherBtn: 'Check Current Weather',
    findMarketsBtn: 'Find Markets & Buyers',
    getRecommendationsBtn: 'Get Recommendations',
    selectSoil: '-- Select Soil --',
    selectSeasonOpt: '-- Select Season --',
    currentMarketPrice: 'Current Market Price (₹/quintal)',
    scanning: 'Scanning...',
    analyzing: 'Analyzing...',
    selectSeason: 'Select Season',
    selectWaterAvail: 'Water Availability',
    soilTypeLabel: 'Soil Type',
    getRecommendations: 'Get Recommendations',
    priceHistoryLabel: 'Historical Prices (Last 6 Months)',
    predictLabelBtn: 'Predict Future Price',
    forecastLabelBtn: 'Forecast Demand',
    forecastSub: 'Visualize future demand trends for key crops',
    marketSub: 'Find the best markets nearby with live pricing data',
    storageSub: 'Determine when to hold and when to sell for maximum profit',
    newsTitle: 'Agriculture News',
    newsSubtitle: 'Latest updates on farming, markets, and weather',
    yojanaTitle: 'Government Schemes',
    yojanaSubtitle: 'Financial aid and insurance for farmers',
    voiceAssistant: 'Voice Assistant',
    listening: 'Listening...',
    tapToSpeak: 'Tap to Speak',
    trySaying: 'Try saying',
    operationalDashboard: 'Operational Dashboard',
    seasonalCalendar: 'Seasonal Crop Calendar',
    fetchingWeather: 'Fetching live weather...',
    nextPrecipitation: 'Next Rain Expected:',
    weeklyTrend: 'Weekly Trend',
    viewFullHistory: 'View Full History',
    yojanaTip: 'Did you know?',
    yojanaTipDesc: 'Registering for PM-KISAN guarantees ₹6,000 every year directly to your bank account.',
    eligibility: 'Eligibility Criteria',
    howToApply: 'How to Apply',
    visitOfficial: 'Visit Official Portal',
    lastUpdated: 'Last Updated',
    loadingNews: 'Loading latest news...',
    noNews: 'No news found for this category.',
    loadingSchemes: 'Loading government schemes...',
    noSchemes: 'No schemes found.',
    logout: 'Logout'
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    pricePrediction: 'मूल्य भविष्यवाणी',
    demandForecast: 'मांग पूर्वानुमान',
    marketLocator: 'बाजार लोकेटर',
    cropAdvisor: 'फसल सलाहकार',
    storageAdvice: 'भंडारण सलाह',
    news: 'समाचार',
    yojana: 'सरकारी योजनाएं',
    livePriceTracker: 'लाइव मूल्य ट्रैकर',
    currentWeather: 'वर्तमान मौसम',
    moisture: 'नमी',
    phLevel: 'पीएच (pH) स्तर',
    activityLog: 'गतिविधि लॉग',
    today: 'आज',
    yesterday: 'कल',
    automatedIrrigation: 'स्वचालित सिंचाई',
    irrigationDone: 'ज़ोन ए की सिंचाई सफलतापूर्वक पूरी हुई।',
    nitrogenApplication: 'नाइट्रोजन आवेदन',
    nitrogenDone: 'सेक्टर 3 में नाइट्रोजन उर्वरक लगाया।',
    activeAlerts: 'सक्रिय अलर्ट',
    frostWarning: 'पाले की चेतावनी (रात)',
    frostDesc: 'आज रात तापमान 4°C से नीचे जा रहा है। संवेदनशील फसलों को बचाएं।',
    irrigationReminder: 'सिंचाई अनुस्मारक',
    irrigationDesc: 'ज़ोन बी में मिट्टी की नमी कम हो रही है।',
    farmManager: 'फार्म प्रबंधक',
    profileSettings: 'प्रोफ़ाइल सेटिंग्स',
    optimalRange: 'इष्टतम सीमा: 60-70%',
    nutrientIndex: 'पोषक तत्व सूचकांक',
    nutrientDesc: 'विस्तृत एनपीके अनुपात विश्लेषण देखें',
    partlyCloudy: 'आंशिक रूप से बादल',
    humidity: 'उमस',
    rainfall: 'वर्षा',
    wind: 'हवा',
    perQuintal: 'प्रति क्विंटल',
    cropSubstitle: 'अपने पर्यावरण के आधार पर व्यक्तिगत फसल सुझाव प्राप्त करें',
    checkWeatherBtn: 'वर्तमान मौसम की जाँच करें',
    findMarketsBtn: 'बाजार और खरीदार खोजें',
    getRecommendationsBtn: 'सिफारिशें प्राप्त करें',
    selectSoil: '-- मिट्टी चुनें --',
    selectSeasonOpt: '-- मौसम चुनें --',
    currentMarketPrice: 'वर्तमान बाजार मूल्य (₹/क्विंटल)',
    scanning: 'स्कैन कर रहा है...',
    analyzing: 'विश्लेषण कर रहा है...',
    selectSeason: 'मौसम का चयन करें',
    selectWaterAvail: 'पानी की उपलब्धता',
    soilTypeLabel: 'मिट्टी का प्रकार',
    getRecommendations: 'सिफारिशें प्राप्त करें',
    priceHistoryLabel: 'ऐतिहासिक कीमतें (पिछले 6 महीने)',
    predictLabelBtn: 'भविष्य की कीमत का अनुमान लगाएं',
    forecastLabelBtn: 'मांग का पूर्वानुमान लगाएं',
    forecastSub: 'प्रमुख फसलों के भविष्य की मांग प्रवृत्तियों की कल्पना करें',
    marketSub: 'लाइव मूल्य डेटा के साथ पास के सर्वोत्तम बाजार खोजें',
    storageSub: 'अधिकतम लाभ के लिए कब रोकें और कब बेचें यह निर्धारित करें',
    'Crop Prices Rising Due to Delayed Monsoons': 'देरी से मानसून के कारण फसल की कीमतें बढ़ रही हैं',
    'Better profits expected this season for drought-resistant crops like Bajra and Jowar.': 'इस मौसम में बाजरा और ज्वार जैसी सूखा प्रतिरोधी फसलों के लिए बेहतर मुनाफे की उम्मीद है।',
    'New Farming Scheme: PM-KUSUM Expanding': 'नई कृषि योजना: पीएम-कुसुम का विस्तार',
    'Government introduces 90% subsidy for solar irrigation pumps in arid regions.': 'सरकार ने शुष्क क्षेत्रों में सौर सिंचाई पंपों के लिए 90% सब्सिडी पेश की।',
    'Tomato Prices Crash in Karnataka Mandis': 'कर्नाटक की मंडियों में टमाटर के दाम गिरे',
    'Excess supply from Kolar district causes a sharp 18% decline in wholesale prices.': 'कोलार जिले से अधिक आपूर्ति के कारण थोक कीमतों में 18% की भारी गिरावट आई है।',
    'ICAR Develops High-Yield Wheat Variety': 'ICAR ने उच्च उपज वाली गेहूं की किस्म विकसित की',
    'A new bio-fortified HD-3226 wheat seed promises 20% higher yield and better disease resistance.': 'एक नया बायो-फोर्टिफाइड HD-3226 गेहूं का बीज 20% अधिक उपज और बेहतर रोग प्रतिरोधक क्षमता का वादा करता है।',
    'Monsoon Forecast: Heavy Showers in Central India': 'मानसून पूर्वानुमान: मध्य भारत में भारी बारिश',
    'IMD has predicted above-normal rainfall starting next week. Farmers advised to delay sowing.': 'आईएमडी ने अगले सप्ताह से सामान्य से बारिश की भविष्यवाणी की है। किसानों को बुवाई में देरी करने की सलाह दी गई है।',
    newsSubtitle: 'खेती, बाजार और मौसम पर नवीनतम अपडेट',
    yojanaTitle: 'सरकारी योजनाएं',
    yojanaSubtitle: 'किसानों के लिए वित्तीय सहायता और बीमा',
    voiceAssistant: 'वॉयस असिस्टेंट',
    listening: 'सुन रहा हूं...',
    tapToSpeak: 'बोलने के लिए टैप करें',
    trySaying: 'यह कहने का प्रयास करें',
    operationalDashboard: 'परिचालन डैशबोर्ड',
    seasonalCalendar: 'मौसमी फसल कैलेंडर',
    fetchingWeather: 'लाइव मौसम को प्राप्त किया जा रहा है...',
    nextPrecipitation: 'अगली बारिश की उम्मीद:',
    weeklyTrend: 'साप्ताहिक प्रवृत्ति',
    viewFullHistory: 'पूरा इतिहास देखें',
    yojanaTip: 'क्या आप जानते हैं?',
    yojanaTipDesc: 'PM-KISAN के लिए पंजीकरण करने पर हर साल ₹6,000 सीधे आपके बैंक खाते में आने की गारंटी है।',
    eligibility: 'पात्रता मानदंड',
    howToApply: 'आवेदन कैसे करें',
    visitOfficial: 'आधिकारिक पोर्टल पर जाएं',
    lastUpdated: 'अंतिम अपडेट',
    loadingNews: 'नवीनतम समाचार लोड हो रहे हैं...',
    noNews: 'इस श्रेणी के लिए कोई समाचार नहीं मिला।',
    loadingSchemes: 'सरकारी योजनाएं लोड हो रही हैं...',
    noSchemes: 'कोई योजना नहीं मिली।',
    logout: 'लॉग आउट'
  },
  mr: {
    dashboard: 'डॅशबोर्ड',
    pricePrediction: 'किंमत अंदाज',
    demandForecast: 'मागणीचा अंदाज',
    marketLocator: 'बाजार शोधक',
    cropAdvisor: 'पीक सल्लागार',
    storageAdvice: 'स्टोरेज सल्ला',
    news: 'बातमी',
    yojana: 'सरकारी योजना',
    livePriceTracker: 'थेट किंमत ट्रॅकर',
    currentWeather: 'सध्याचे हवामान',
    moisture: 'ओलावा',
    phLevel: 'पीएच (pH) पातळी',
    activityLog: 'क्रियाकलाप लॉग',
    today: 'आज',
    yesterday: 'काल',
    automatedIrrigation: 'स्वयंचलित सिंचन',
    irrigationDone: 'झोन ए चे सिंचन यशस्वीरित्या पूर्ण झाले.',
    nitrogenApplication: 'नायट्रोजनचा वापर',
    nitrogenDone: 'सेक्टर 3 मध्ये नायट्रोजन खत लागू केले.',
    activeAlerts: 'सक्रिय सूचना',
    frostWarning: 'दंव चेतावणी (रात्र)',
    frostDesc: 'आज रात्री तापमान 4°C च्या खाली जात आहे. संवेदनशील पिकांचे संरक्षण करा.',
    irrigationReminder: 'सिंचन स्मरणपत्र',
    irrigationDesc: 'झोन बी मध्ये जमिनीतील ओलावा कमी होत आहे.',
    farmManager: 'शेत व्यवस्थापक',
    profileSettings: 'प्रोफाइल सेटिंग्ज',
    optimalRange: 'इष्टतम श्रेणी: 60-70%',
    nutrientIndex: 'पोषक तत्व निर्देशांक',
    nutrientDesc: 'तपशीलवार NPK प्रमाण विश्लेषण पहा',
    partlyCloudy: 'अंशतः ढगाळ',
    humidity: 'आर्द्रता',
    rainfall: 'पाऊस',
    wind: 'वारा',
    perQuintal: 'प्रति क्विंटल',
    cropSubstitle: 'तुमच्या वातावरणावर आधारित वैयक्तिकृत पीक सूचना मिळवा',
    checkWeatherBtn: 'सध्याचे हवामान तपासा',
    selectSeason: 'हंगाम निवडा',
    selectWaterAvail: 'पाण्याची उपलब्धता',
    soilTypeLabel: 'मातीचा प्रकार',
    getRecommendations: 'शिफारसी मिळवा',
    priceHistoryLabel: 'ऐतिहासिक किमती (गेले ६ महिने)',
    predictLabelBtn: 'भविष्यातील किमतीचा अंदाज लावा',
    forecastLabelBtn: 'मागणीचा अंदाज लावा',
    forecastSub: 'प्रमुख पिकांसाठी भविष्यातील मागणीच्या ट्रेंडची कल्पना करा',
    marketSub: 'थेट किंमत डेटासह जवळील सर्वोत्तम बाजारपेठा शोधा',
    storageSub: 'कमाल नफ्यासाठी केव्हा ठेवायचे आणि केव्हा विकायचे ते ठरवा',
    newsTitle: 'कृषी बातम्या',
    newsSubtitle: 'शेती, बाजार आणि हवामानावरील नवीनतम अपडेट्स',
    yojanaTitle: 'सरकारी योजना',
    yojanaSubtitle: 'शेतकऱ्यांसाठी आर्थिक मदत आणि विमा',
    voiceAssistant: 'आवाज सहाय्यक',
    listening: 'ऐकत आहे...',
    tapToSpeak: 'बोलण्यासाठी टॅप करा',
    trySaying: 'हे सांगून पहा',
    operationalDashboard: 'ऑपरेशनल डॅशबोर्ड',
    seasonalCalendar: 'हंगामी पीक कॅलेंडर',
    fetchingWeather: 'थेट हवामान आणत आहे...',
    nextPrecipitation: 'पुढील पावसाची अपेक्षा:',
    weeklyTrend: 'साप्ताहिक ट्रेंड',
    viewFullHistory: 'संपूर्ण इतिहास पहा',
    yojanaTip: 'तुम्हाला माहीत आहे का?',
    yojanaTipDesc: 'PM-KISAN साठी नोंदणी केल्याने दरवर्षी ₹6,000 थेट तुमच्या बँक खात्यात मिळण्याची हमी मिळते.',
    eligibility: 'पात्रता निकष',
    howToApply: 'अर्ज कसा करायचा',
    visitOfficial: 'अधिकृत पोर्टलला भेट द्या',
    lastUpdated: 'शेवटचे अद्यतनित',
    loadingNews: 'ताज्या बातम्या लोड करत आहे...',
    noNews: 'या श्रेणीसाठी कोणत्याही बातम्या नाहीत.',
    loadingSchemes: 'सरकारी योजना लोड करत आहे...',
    noSchemes: 'कोणतीही योजना सापडली नाही.',
    logout: 'लॉग आउट'
  },
  te: {
    dashboard: 'డాష్‌బోర్డ్',
    pricePrediction: 'ధర అంచనా',
    demandForecast: 'డిమాండ్ అంచనా',
    marketLocator: 'మార్కెట్ లొకేటర్',
    cropAdvisor: 'పంట సలహాదారు',
    storageAdvice: 'నిల్వ సలహా',
    news: 'వార్తలు',
    yojana: 'పథకాలు',
    livePriceTracker: 'ప్రత్యక్ష ధర ట్రాకర్',
    currentWeather: 'ప్రస్తుత వాతావరణం',
    moisture: 'తేమ',
    phLevel: 'pH స్థాయి',
    activityLog: 'కార్యకలాప లాగ్',
    logout: 'లాగ్అవుట్'
  },
  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    pricePrediction: 'ಬೆಲೆ ಮುನ್ಸೂಚನೆ',
    demandForecast: 'ಬೇಡಿಕೆ ಮುನ್ಸೂಚನೆ',
    marketLocator: 'ಮಾರುಕಟ್ಟೆ ಶೋಧಕ',
    cropAdvisor: 'ಬೆಳೆ ಸಲಹೆಗಾರ',
    storageAdvice: 'ಶೇಖರಣಾ ಸಲಹೆ',
    news: 'ಸುದ್ದಿ',
    yojana: 'ಯೋಜನೆಗಳು',
    livePriceTracker: 'ಲೈವ್ ಬೆಲೆ ಟ್ರ್ಯಾಕರ್',
    currentWeather: 'ಪ್ರಸ್ತುತ ಹವಾಮಾನ',
    moisture: 'ತೇವಾಂಶ',
    phLevel: 'pH ಮಟ್ಟ',
    activityLog: 'ಚಟುವಟಿಕೆ ಲಾಗ್',
    logout: 'ಲಾಗ್ಔಟ್'
  }
};

const LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' }
];

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('agri_language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('agri_language', language);
  }, [language]);

  const t = (key) => {
    if (translations[language] && translations[language][key]) {
      return translations[language][key];
    }
    // Fallback to English if key doesn't exist in the selected language
    if (translations['en'] && translations['en'][key]) {
      return translations['en'][key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage: setLanguage, t, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
